### ISSUE TITLE
problem building html documentation

### ISSUE THREAD

**Issue by prjemian** [prjemian/spec2nexus#120]
# Error report
This problem reported while building document on Windows or Linux:

```
$ make html
Running Sphinx v1.6.2

Exception occurred:
  File "/.../anaconda/lib/python2.7/site-packages/six.py", line 194, in load_module
    return sys.modules[fullname]
AttributeError: 'NoneType' object has no attribute 'modules'
The full traceback has been saved in /tmp/sphinx-err-brL8Tf.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
```

# Log file contents

```
# Sphinx version: 1.6.2
# Python version: 2.7.11 (CPython)
# Docutils version: 0.12 release
# Jinja2 version: 2.7.3
# Last messages:

# Loaded extensions:
Traceback (most recent call last):
  File "/.../anaconda/lib/python2.7/site-packages/Sphinx-1.6.2-py2.7.egg/sphinx/cmdline.py", line 305, in main
    opts.warningiserror, opts.tags, opts.verbosity, opts.jobs)
  File "/.../anaconda/lib/python2.7/site-packages/Sphinx-1.6.2-py2.7.egg/sphinx/application.py", line 192, in __init__
    self.setup_extension(extension)
  File "/.../anaconda/lib/python2.7/site-packages/Sphinx-1.6.2-py2.7.egg/sphinx/application.py", line 456, in setup_extension
    self.registry.load_extension(self, extname)
  File "/.../anaconda/lib/python2.7/site-packages/Sphinx-1.6.2-py2.7.egg/sphinx/registry.py", line 196, in load_extension
    mod = __import__(extname, None, None, ['setup'])
  File "/.../anaconda/lib/python2.7/site-packages/Sphinx-1.6.2-py2.7.egg/sphinx/builders/applehelp.py", line 19, in <module>
    from sphinx.builders.html import StandaloneHTMLBuilder
  File "/.../anaconda/lib/python2.7/site-packages/Sphinx-1.6.2-py2.7.egg/sphinx/builders/html.py", line 45, in <module>
    from sphinx.theming import HTMLThemeFactory
  File "/.../anaconda/lib/python2.7/site-packages/Sphinx-1.6.2-py2.7.egg/sphinx/theming.py", line 21, in <module>
    from six.moves import configparser
  File "/.../anaconda/lib/python2.7/site-packages/six.py", line 194, in load_module
    return sys.modules[fullname]
AttributeError: 'NoneType' object has no attribute 'modules'
```

**Comment by prjemian** [comment]
# Windows log file
On windows, the error is different (but first two calls are the same):

```
# Sphinx version: 1.4.8
# Python version: 2.7.13 (CPython)
# Docutils version: 0.12 release
# Jinja2 version: 2.8
# Last messages:

# Loaded extensions:
Traceback (most recent call last):
  File "D:\Apps\Anaconda\lib\site-packages\Sphinx-1.4.8-py2.7.egg\sphinx\cmdline.py", line 243, in main
    opts.warningiserror, opts.tags, opts.verbosity, opts.jobs)
  File "D:\Apps\Anaconda\lib\site-packages\Sphinx-1.4.8-py2.7.egg\sphinx\application.py", line 163, in __init__
    self.setup_extension(extension)
  File "D:\Apps\Anaconda\lib\site-packages\Sphinx-1.4.8-py2.7.egg\sphinx\application.py", line 473, in setup_extension
    mod = __import__(extension, None, None, ['setup'])
  File "D:\Apps\Anaconda\lib\site-packages\Sphinx-1.4.8-py2.7.egg\sphinx\ext\autodoc.py", line 29, in <module>
    from sphinx.pycode import ModuleAnalyzer, PycodeError
  File "D:\Apps\Anaconda\lib\site-packages\Sphinx-1.4.8-py2.7.egg\sphinx\pycode\__init__.py", line 38, in <module>
    for k, v in iteritems(pygrammar.symbol2number):
TypeError: 'Mock' object is not iterable
```

**Comment by prjemian** [comment]
after updating sphinx in windows, same error as Linux reports:

```
# Sphinx version: 1.6.3
# Python version: 2.7.13 (CPython)
# Docutils version: 0.12 release
# Jinja2 version: 2.8
# Last messages:

# Loaded extensions:
Traceback (most recent call last):
  File "D:\Apps\Anaconda\lib\site-packages\Sphinx-1.6.3-py2.7.egg\sphinx\cmdline.py", line 305, in main
    opts.warningiserror, opts.tags, opts.verbosity, opts.jobs)
  File "D:\Apps\Anaconda\lib\site-packages\Sphinx-1.6.3-py2.7.egg\sphinx\application.py", line 192, in __init__
    self.setup_extension(extension)
  File "D:\Apps\Anaconda\lib\site-packages\Sphinx-1.6.3-py2.7.egg\sphinx\application.py", line 456, in setup_extension
    self.registry.load_extension(self, extname)
  File "D:\Apps\Anaconda\lib\site-packages\Sphinx-1.6.3-py2.7.egg\sphinx\registry.py", line 196, in load_extension
    mod = __import__(extname, None, None, ['setup'])
  File "D:\Apps\Anaconda\lib\site-packages\Sphinx-1.6.3-py2.7.egg\sphinx\builders\applehelp.py", line 19, in <module>
    from sphinx.builders.html import StandaloneHTMLBuilder
  File "D:\Apps\Anaconda\lib\site-packages\Sphinx-1.6.3-py2.7.egg\sphinx\builders\html.py", line 45, in <module>
    from sphinx.theming import HTMLThemeFactory
  File "D:\Apps\Anaconda\lib\site-packages\Sphinx-1.6.3-py2.7.egg\sphinx\theming.py", line 21, in <module>
    from six.moves import configparser
  File "D:\Apps\Anaconda\lib\site-packages\six.py", line 198, in load_module
    return sys.modules[fullname]
AttributeError: 'NoneType' object has no attribute 'modules'
```

**Comment by prjemian** [comment]
Still there now (testing with py27):

```
    def load_module(self, fullname):
        try:
            # in case of a reload
            return sys.modules[fullname]
```

So, why does `sys` have the value `None`?  Comes from the `six` package.

**Comment by prjemian** [comment]
Not sure this problem is fixable.

```
# Sphinx version: 1.7.4
# Python version: 2.7.15 (CPython)
# Docutils version: 0.14 
# Jinja2 version: 2.10
# Last messages:

# Loaded extensions:
Traceback (most recent call last):
  File "/home/mintadmin/Apps/anaconda/lib/python2.7/site-packages/sphinx/cmdline.py", line 303, in main
    args.warningiserror, args.tags, args.verbosity, args.jobs)
  File "/home/mintadmin/Apps/anaconda/lib/python2.7/site-packages/sphinx/application.py", line 187, in __init__
    self.setup_extension(extension)
  File "/home/mintadmin/Apps/anaconda/lib/python2.7/site-packages/sphinx/application.py", line 411, in setup_extension
    self.registry.load_extension(self, extname)
  File "/home/mintadmin/Apps/anaconda/lib/python2.7/site-packages/sphinx/registry.py", line 315, in load_extension
    mod = __import__(extname, None, None, ['setup'])
  File "/home/mintadmin/Apps/anaconda/lib/python2.7/site-packages/sphinx/builders/applehelp.py", line 20, in <module>
    from sphinx.builders.html import StandaloneHTMLBuilder
  File "/home/mintadmin/Apps/anaconda/lib/python2.7/site-packages/sphinx/builders/html.py", line 42, in <module>
    from sphinx.theming import HTMLThemeFactory
  File "/home/mintadmin/Apps/anaconda/lib/python2.7/site-packages/sphinx/theming.py", line 21, in <module>
    from six.moves import configparser
  File "/home/mintadmin/Apps/anaconda/lib/python2.7/site-packages/six.py", line 198, in load_module
    return sys.modules[fullname]
AttributeError: 'NoneType' object has no attribute 'modules'
```

will try creating a new `conf.py` that is consistent with current sphinx version

**Comment by prjemian** [comment]
Creating a new `conf.py` file using current sphinx-quickstart is useful.  The root cause of this issue is due to changes in the code that avoids documenting common packages such as matplotlib, numpy...  The *mock* process has changed.

**Comment by prjemian** [comment]
Ultimately, must not mock the `six` package.  Hope this will be OK for RTD.
