### ISSUE TITLE
ValueError: invalid literal for int() with base 10: '35.1'

### ISSUE THREAD

**Issue by prjemian** [prjemian/spec2nexus#128]
probably legacy of using strings to represent scan numbers - hrmph, related to #39, #41, & #46

```
usaxs@usaxscontrol .../local_livedata/specplots $ tail -f specplots.log 
[specplotsAllScans.py 31087 2018-08-20 11:30:02.921802] faulthandler: module enabled
Traceback (most recent call last):
  File "/home/beams/USAXS/Documents/eclipse/USAXS/livedata/specplotsAllScans.py", line 344, in <module>
    plotAllSpecFileScans(specFile)
  File "/home/beams/USAXS/Documents/eclipse/USAXS/livedata/specplotsAllScans.py", line 127, in plotAllSpecFileScans
    for scan_number in sd.getScanNumbers():
  File "/APSshare/anaconda/x86_64/lib/python2.7/site-packages/spec2nexus/spec.py", line 294, in getScanNumbers
    return sorted(self.scans.keys(), key=int)
ValueError: invalid literal for int() with base 10: '35.1'
#= 31073 --Done---------------------------------- Mon Aug 20 11:30:03 CDT 2018
```

**Comment by prjemian** [comment]
@jilavsky : this describes the problem that the SPEC plots are not updating.  The repair involves a change to the spec2nexus library used by the `USAXS/livedata/specplotsAllScans.py` code that is used.

**But**, the problem is provoked because the SPEC data file has two header blocks in it.  Best advice is to always use a new file name when calling SPEC's `newplot` command.  First notice of this error for you was `2018-08-13 14:10:02.904380` (from the logs).

**Comment by prjemian** [comment]
@jilavsky:  These are the `#F` lines in the current SPEC data files.  There are two with more than one header block.  Since there is more than one such file, emphasize that a *new* file name should be given when `newfile` is called in SPEC. 

```
usaxs@usaxscontrol .../USAXS_data/2018-08 $ grep \#F *.dat
08_02_IN625_800C.dat:#F 08_02_IN625_800C.dat
08_02_setup.dat:#F 08_02_setup.dat
08_03_nist.dat:#F 08_03_nist.dat
08_03_WR625_870C.dat:#F 08_03_WR625_870C.dat
08_03_ZrCoFe.dat:#F 08_03_ZrCoFe.dat
08_03_ZrCoFe.dat:#F 08_03_ZrCoFe.dat
08_04_AgBigSphere.dat:#F 08_04_AgBigSphere.dat
08_04_AgWire.dat:#F 08_04_AgWire.dat
08_04_AM_cement.dat:#F 08_04_AM_cement.dat
08_05_AM_cement2.dat:#F 08_05_AM_cement2.dat
08_05_NIST_static2.dat:#F 08_05_NIST_static2.dat
08_05_NIST_static.dat:#F 08_05_NIST_static.dat
08_07_anode1097b.dat:#F 08_07_anode1097b.dat
08_07_anode1100.dat:#F 08_07_anode1100.dat
08_07_anodereact.dat:#F 08_07_anodereact.dat
08_08_anode1097c.dat:#F 08_08_anode1097c.dat
08_08_anode1105.dat:#F 08_08_anode1105.dat
08_08_MailIn.dat:#F 08_08_MailIn.dat
08_08_Park.dat:#F 08_08_Park.dat
08_09_mang.dat:#F 08_09_mang.dat
08_10_Vlachos.dat:#F 08_10_Vlachos.dat
08_12_Myers.dat:#F 08_12_Myers.dat
08_13_Antonin2.dat:#F 08_13_Antonin2.dat
08_13_Antonin.dat:#F 08_13_Antonin.dat
08_13_Antonin.dat:#F 08_13_Antonin.dat
08_13_Cai.dat:#F 08_13_Cai.dat
08_13_Felicity.dat:#F 08_13_Felicity.dat
08_13_Felicity.dat:#F 08_13_Felicity.dat
08_13_Felicity.dat:#F 08_13_Felicity.dat
08_13_Goody.dat:#F 08_13_Goody.dat
08_13_Jhalaria.dat:#F 08_13_Jhalaria.dat
08_13_Jiehua.dat:#F 08_13_Jiehua.dat
08_13_NIST.dat:#F 08_13_NIST.dat
08_14_Aparna.dat:#F 08_14_Aparna.dat
08_14_Meysam.dat:#F 08_14_Meysam.dat
08_14_NIST.dat:#F 08_14_NIST.dat
08_14_RyanFox.dat:#F 08_14_RyanFox.dat
08_14_Sai.dat:#F 08_14_Sai.dat
08_15_Felicity120D.dat:#F 08_15_Felicity120D.dat
08_15_Murali.dat:#F 08_15_Murali.dat
08_16_INL_Cheng.dat:#F 08_16_INL_Cheng.dat
08_16_Murali2.dat:#F 08_16_Murali2.dat
08_17_Gadikota.dat:#F 08_17_Gadikota.dat
08_17_MeysamNMR.dat:#F 08_17_MeysamNMR.dat
08_17_Sanders.dat:#F 08_17_Sanders.dat
08_19_Murali3.dat:#F 08_19_Murali3.dat
08_20_Dai.dat:#F 08_20_Dai.dat
08_20_Leighanne.dat:#F 08_20_Leighanne.dat
```

**Comment by prjemian** [comment]
The (existing) *CdOsO* example data file has two such `#F` blocks

**Comment by prjemian** [comment]
This excerpt shows the problem (to resolve in spec2nexus) clearly:

```
In [2]: from spec2nexus.spec import *                                                                                               

In [5]: sdf = SpecDataFile("CdOsO")                                                                                                 

In [6]: sdf.getScanNumbers()                                                                                                        
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-6-8ac143344875> in <module>
----> 1 sdf.getScanNumbers()

~/Documents/eclipse/spec2nexus/src/spec2nexus/spec.py in getScanNumbers(self)
    292     def getScanNumbers(self):
    293         """return a list of all scan numbers sorted by scan number"""
--> 294         return sorted(self.scans.keys(), key=int)
    295 
    296     def getScanNumbersChronological(self):

ValueError: invalid literal for int() with base 10: '1.1'

In [7]:                                                                                                                             
```
