### ISSUE TITLE
DuplicateSpecScanNumber with multiple #F sections

### ISSUE THREAD

**Issue by prjemian** [prjemian/spec2nexus#142]
When processing a SPEC file created by [apstools SPEC file writer](https://apstools.readthedocs.io/en/latest/source/filewriters.html#apstools.filewriters.SpecWriterCallback), and the file contains many `#F` lines, this exception trace was reported:

```
Traceback (most recent call last):
  File "/home/beams11/USAXS/Documents/eclipse/USAXS/livedata/scanplots.py", line 437, in <module>
    main()
  File "/home/beams11/USAXS/Documents/eclipse/USAXS/livedata/scanplots.py", line 406, in main
    _scans = last_n_scans(SCANLOG, n)    # updates scan_cache & spec_file_cache
  File "/home/beams11/USAXS/Documents/eclipse/USAXS/livedata/scanplots.py", line 268, in last_n_scans
    scan_object = plottable_scan(scan_node)
  File "/home/beams11/USAXS/Documents/eclipse/USAXS/livedata/scanplots.py", line 207, in plottable_scan
    scan_node.attrib['id'],
  File "/home/beams11/USAXS/Documents/eclipse/USAXS/livedata/scanplots.py", line 125, in setFileParms
    self.safe_id = self.makeSafeId()
  File "/home/beams11/USAXS/Documents/eclipse/USAXS/livedata/scanplots.py", line 130, in makeSafeId
    self.getData()
  File "/home/beams11/USAXS/Documents/eclipse/USAXS/livedata/scanplots.py", line 157, in getData
    self.spec_scan = self.getSpecScan()
  File "/home/beams11/USAXS/Documents/eclipse/USAXS/livedata/scanplots.py", line 150, in getSpecScan
    spec = spec_file_cache.get(self.data_file)
  File "/home/beams11/USAXS/Documents/eclipse/USAXS/livedata/scanplots.py", line 92, in get
    return self._add_(specfile).sdf_object
  File "/home/beams11/USAXS/Documents/eclipse/USAXS/livedata/scanplots.py", line 76, in _add_
    self.db[specfile] = SpecFileObject(specfile)
  File "/home/beams11/USAXS/Documents/eclipse/USAXS/livedata/scanplots.py", line 63, in __init__
    self.sdf_object = SpecDataFile(specfile)
  File "/APSshare/anaconda/x86_64/lib/python2.7/site-packages/spec2nexus/spec.py", line 214, in __init__
    self.read()
  File "/APSshare/anaconda/x86_64/lib/python2.7/site-packages/spec2nexus/spec.py", line 259, in read
    self.plugin_manager.process(key, part, self)
  File "/APSshare/anaconda/x86_64/lib/python2.7/site-packages/spec2nexus/plugin.py", line 305, in process
    handler().process(*args, **kw)
  File "/APSshare/anaconda/x86_64/lib/python2.7/site-packages/spec2nexus/plugins/spec_common_spec2nexus.py", line 204, in process
    raise DuplicateSpecScanNumber(msg)
spec2nexus.spec.DuplicateSpecScanNumber: 1 in /share1/USAXS_data/2019-05/05_02_test.dat
```

Here's the data file:  
[05_02_test.dat.txt](https://github.com/prjemian/spec2nexus/files/3142568/05_02_test.dat.txt)

**Comment by prjemian** [comment]
Fails on the first scan after the second `#F` line.  Ultimately, the failure is due to these lines:

https://github.com/prjemian/spec2nexus/blob/master/src/spec2nexus/plugins/spec_common_spec2nexus.py#L196-L197

It's an *off by 1* error.  The `range()` should start from zero and `i` should be `i+1` in the second line.
