### ISSUE TITLE
unit test errors with py3.6

### ISSUE THREAD

**Issue by prjemian** [prjemian/spec2nexus#146]
relates to #123

## Problem 1.

`module 'matplotlib' has no attribute 'figure'`

## Problem 2.

also (from [travis-ci](https://travis-ci.org/prjemian/spec2nexus/jobs/533133395))

```
======================================================================
ERROR: test_isSpecFile (tests.test_spec.Test)
test all the known data files to see if they are SPEC
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests/../tests/test_spec.py", line 64, in test_isSpecFile
    self.assertFalse(self.is_spec_file('compression.h5'))
  File "tests/../tests/test_spec.py", line 49, in is_spec_file
    return spec.is_spec_file(self.abs_data_fname(fname))
  File "/home/travis/build/prjemian/spec2nexus/src/spec2nexus/spec.py", line 157, in is_spec_file
    for line in fp.readlines():
  File "/home/travis/miniconda/envs/travis-3.6/lib/python3.6/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x89 in position 0: invalid start byte

======================================================================
FAIL: test_command_line_spec_data_file_02_03_setup (tests.test_specplot_gallery.SpecPlotGallery)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests/../tests/test_specplot_gallery.py", line 125, in test_command_line_spec_data_file_02_03_setup
    self.assertTrue(os.path.exists(plotDir))
AssertionError: False is not true
======================================================================
FAIL: test_command_line_spec_data_file_03_06_JanTest (tests.test_specplot_gallery.SpecPlotGallery)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests/../tests/test_specplot_gallery.py", line 107, in test_command_line_spec_data_file_03_06_JanTest
    self.assertTrue(os.path.exists(plotDir))
AssertionError: False is not true
======================================================================
FAIL: test_command_line_spec_data_file_33bm_spec (tests.test_specplot_gallery.SpecPlotGallery)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests/../tests/test_specplot_gallery.py", line 75, in test_command_line_spec_data_file_33bm_spec
    self.assertTrue(os.path.exists(plotDir))
AssertionError: False is not true
======================================================================
FAIL: test_command_line_spec_data_file_list (tests.test_specplot_gallery.SpecPlotGallery)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests/../tests/test_specplot_gallery.py", line 141, in test_command_line_spec_data_file_list
    self.assertTrue(os.path.exists(plotDir))
AssertionError: False is not true
======================================================================
```

**Comment by prjemian** [comment]
Problem 1 needs additional `import matplotlib.figure`

**Comment by prjemian** [comment]
Problem 2 is trickier.  When trying to read an HDF5 file as a SPEC data file, the exception shown is raised when actually any exception should cause the routine to return False (the file is not a SPEC data file).

**Comment by prjemian** [comment]
Changesets 57e39e and 1f674bf are part of this issue

**Comment by prjemian** [comment]
Yay!  travis-ci completed with no unit test errors for [py27, py35, py36, & py37](https://travis-ci.org/prjemian/spec2nexus/builds/533153522?utm_source=github_status&utm_medium=notification)
