### ISSUE TITLE
travis-ci build problem: py27 only

### ISSUE THREAD

**Issue by prjemian** [prjemian/spec2nexus#183]
while working on #181, [travis-ci](https://travis-ci.org/prjemian/spec2nexus/jobs/561904084) reports a build problem *only* for py27:

```
0.27s$ coverage run tests/
Traceback (most recent call last):
  File "tests/__main__.py", line 18, in <module>
    runner.run(__init__.suite())
  File "tests/__init__.py", line 33, in suite
    from tests import test_plugin
  File "tests/../tests/test_plugin.py", line 26, in <module>
    from spec2nexus import plugins
  File "/home/travis/build/prjemian/spec2nexus/src/spec2nexus/plugins/__init__.py", line 11, in <module>
    from . import spec_common
  File "/home/travis/build/prjemian/spec2nexus/src/spec2nexus/plugins/spec_common.py", line 42, in <module>
    class SPEC_File(ControlLineHandler):
  File "/home/travis/miniconda/envs/travis-2.7/lib/python2.7/site-packages/six.py", line 849, in wrapper
    return metaclass(cls.__name__, cls.__bases__, orig_vars)
  File "/home/travis/build/prjemian/spec2nexus/src/spec2nexus/plugin.py", line 125, in __init__
    manager = get_plugin_manager()
  File "/home/travis/build/prjemian/spec2nexus/src/spec2nexus/plugin.py", line 100, in get_plugin_manager
    plugin_manager.load_plugins()
  File "/home/travis/build/prjemian/spec2nexus/src/spec2nexus/plugin.py", line 218, in load_plugins
    from . import plugins   # issue #166: plugins are loaded here, NOT any earlier!
ImportError: cannot import name plugins
The command "coverage run tests/" exited with 1.
```

Also, the local build is saying that utils cannot import numpy, something odd here

**Comment by prjemian** [comment]
switched to a different local build and confirm that same error as travis for the py27 tests

**Comment by prjemian** [comment]
changeset 073e3f6 belongs here

**Comment by prjemian** [comment]
All tests OK now: https://travis-ci.org/prjemian/spec2nexus/builds/561918439
