### ISSUE TITLE
in file startup_1.spec, check that all #L lines are correct

### ISSUE THREAD

**Issue by prjemian** [prjemian/spec2nexus#188]
While building unit tests for #51, it was discovered that (at least for) scans 52 and 53 in file `startup_1.spec`, IndexError was raised:

```
Traceback (most recent call last):
  File "/home/mintadmin/Documents/eclipse/spec2nexus/tests/test_diffractometers.py", line 139, in test_src_spec2nexus_data
    geom = dgc.match(scan)
  File "/home/mintadmin/Documents/eclipse/spec2nexus/src/spec2nexus/diffractometers.py", line 121, in match
    scan_G0 = scan.G['G0'].split()
  File "/home/mintadmin/Documents/eclipse/spec2nexus/src/spec2nexus/spec.py", line 485, in __getattribute__
    self.interpret()
  File "/home/mintadmin/Documents/eclipse/spec2nexus/src/spec2nexus/spec.py", line 519, in interpret
    func(self)
  File "/home/mintadmin/Documents/eclipse/spec2nexus/src/spec2nexus/plugins/spec_common.py", line 880, in postprocess
    data_lines_postprocessing(scan)
  File "/home/mintadmin/Documents/eclipse/spec2nexus/src/spec2nexus/plugins/spec_common.py", line 1223, in data_lines_postprocessing
    buf = scan._interpret_data_row(values)
  File "/home/mintadmin/Documents/eclipse/spec2nexus/src/spec2nexus/spec.py", line 566, in _interpret_data_row
    label = self.L[col]
IndexError: list index out of range
```

**Comment by prjemian** [comment]
It's failing at reading the data at this place in the file:

```
#L TwoTheta  H  K  L  Alpha  Beta  Epoch  seconds  I00  d3  I01  Vor_TotT  Vor_ICR  Vor_OCR  Vor_CalLiveT  Vor_RealT  Vor_Trigger  Vor_Event  Vor_Overf  Vor_Underf  Vor_TrigLiveT  Vor_SCA1  Vor_SCA2  Vor_SCA3  filters  trans  corrdet  Energy  imtot  immax  imroi2  imroi3  imroi4  imsca1  imsca2  imsca3  imsca4  CHI_I  CHI_V  I0  imroi1
15.0391 -0.00547416 -0.0343876 -0.64925 -10.5895 -4.4496 14570.589 0.37224042 23757 56744 48409 10.300978 14948.046 13378.734 4.5070772 5.050104 74592 67372 192 0 4.9900835 490 11597 1595 0 1 36.232907 19.999986 94453561 2027.1739 1106073.9 3692409.8 10404508 1107.6087 1128.2609 1145.6522 1246.7391 4.8863966 4.8647288 2833 102647.83
@0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0\
```

Somehow, it has replaced the `@` with a space and then merged those lines together.  Looks like the MCA plugin has problems.

Also noting these lins in the scan header:

```
#@SCA0	vorsca1	-1	0
#@SCA1	vorsca2	-2	0
#@SCA2	vorsca3	-3	0
#@SCA3	vortrlt	-109	0
#@SCA4	vorcalt	-101	0
#@SCA5	vorrt	-102	0
#@SCA6	voricr	-103	0
#@SCA7	vorocr	-104	0
#@SCA8	vortrig	-105	0
#@SCA9	vorevnt	-106	0
#@SCA10	vorovrf	-107	0
#@SCA11	vorundf	-108	0
```

**Comment by prjemian** [comment]
The data file has no text `MCA` in it but has many lines that start with `@`.  Also, some lines in the header that describe `SCA` parameters (single-channel analyzer).

The reader, *still* should not choke on this file, just parse and retain the `@` lines.  So, there's still work to be done.

**Comment by prjemian** [comment]
No, it has not replaced the `@` with a space, that line is recognized as having an *UNRECOGNIZED_KEY*, handled by the `UnrecognizedControlLine()` plugin.  However the following lines are recognized as data lines.

What got missed is that the lines starting with `@` end with a `\` which signifies that the next line should be appended, and so forth, until a line with no such ending is found.

For data lines, the continuation character is parsed in the plugin:

    dl = '\n'.join(scan.data_lines).replace('\\\n', ' ')

Perhaps it would be better to gather the continued lines earlier, in `spec.py` in the `interpret()` method, just after this line:

    lines = self.raw.splitlines()

**Comment by prjemian** [comment]
er, within that line:  `lines = self.raw.replace('\\\n', ' ').splitlines()`

**Comment by prjemian** [comment]
Any unrecognized data will be written to a NeXus group named `unrecognized`, once the scan's `interpret()` method is called (directly or indirectly due to the `scan.__lazy_interpret__` attribute).
