### ISSUE TITLE
missing documentation for standard plugins

### ISSUE THREAD

**Issue by prjemian** [prjemian/spec2nexus#287]
This page has no content: https://prjemian.github.io/spec2nexus/supplied_plugins/spec_common.html

**Comment by prjemian** [comment]
In local builds, the documentation is not missing, on-line is missing.  Check the [most recent build log](https://pipelines.actions.githubusercontent.com/serviceHosts/351984a3-e641-45cd-a1ac-0f1477854c59/_apis/pipelines/1/runs/58/signedlogcontent/2?urlExpires=2022-09-19T14%3A14%3A20.4629306Z&urlSigningMethod=HMACV1&urlSignature=5Co7mGMBZdRAbgmET7n7kil6oOskl4bSUlK711pkZcw%3D) on GitHub:

<details>

```
2022-09-06T06:39:05.7723967Z Running Sphinx v5.1.1
2022-09-06T06:39:06.1660908Z [autosummary] generating autosummary for: api.rst, applications.rst, changes.rst, charts.rst, contents.rst, control_lines.rst, diffractometers.rst, example_data.rst, extractSpecScan.rst, eznx.rst, ..., supplied_plugins/XPCS.rst, supplied_plugins/apstools_specwriter.rst, supplied_plugins/fallback.rst, supplied_plugins/spec_common.rst, supplied_plugins/uim.rst, supplied_plugins/unicat.rst, supplied_plugins/uxml.rst, unit_testing.rst, utils.rst, writer.rst
2022-09-06T06:39:06.2306263Z Failed to import spec2nexus.charts.
2022-09-06T06:39:06.2307043Z Possible hints:
2022-09-06T06:39:06.2310287Z * ModuleNotFoundError: No module named 'numpy'
2022-09-06T06:39:06.2311112Z * AttributeError: module 'spec2nexus' has no attribute 'charts'
2022-09-06T06:39:06.2314721Z Failed to import spec2nexus.plugins.uxml.
2022-09-06T06:39:06.2315177Z Possible hints:
2022-09-06T06:39:06.2315883Z * AttributeError: module 'spec2nexus.plugins' has no attribute 'uxml'
2022-09-06T06:39:06.2318732Z * ModuleNotFoundError: No module named 'lxml'
2022-09-06T06:39:06.2319823Z Failed to import spec2nexus.specplot_gallery.
2022-09-06T06:39:06.2321343Z Possible hints:
2022-09-06T06:39:06.2322106Z * ModuleNotFoundError: No module named 'numpy'
2022-09-06T06:39:06.2322869Z * AttributeError: module 'spec2nexus' has no attribute 'specplot_gallery'
2022-09-06T06:39:06.2323432Z Failed to import spec2nexus.control_lines.
2022-09-06T06:39:06.2323845Z Possible hints:
2022-09-06T06:39:06.2407875Z * AttributeError: module 'spec2nexus' has no attribute 'control_lines'
2022-09-06T06:39:06.2408686Z * ModuleNotFoundError: No module named 'numpy'
2022-09-06T06:39:06.2410422Z Failed to import spec2nexus.diffractometers.
2022-09-06T06:39:06.2410738Z Possible hints:
2022-09-06T06:39:06.2411250Z * AttributeError: module 'spec2nexus' has no attribute 'diffractometers'
2022-09-06T06:39:06.2411707Z * ModuleNotFoundError: No module named 'numpy'
2022-09-06T06:39:06.2412209Z Failed to import spec2nexus.extractSpecScan.
2022-09-06T06:39:06.2412501Z Possible hints:
2022-09-06T06:39:06.2420427Z * ModuleNotFoundError: No module named 'numpy'
2022-09-06T06:39:06.2421040Z * AttributeError: module 'spec2nexus' has no attribute 'extractSpecScan'
2022-09-06T06:39:06.2421465Z Failed to import spec2nexus.plugins.spec_common.
2022-09-06T06:39:06.2421777Z Possible hints:
2022-09-06T06:39:06.2422144Z * ModuleNotFoundError: No module named 'numpy'
2022-09-06T06:39:06.2422790Z * AttributeError: module 'spec2nexus.plugins' has no attribute 'spec_common'
2022-09-06T06:39:06.2423238Z Failed to import spec2nexus.utils.
2022-09-06T06:39:06.2423490Z Possible hints:
2022-09-06T06:39:06.2423852Z * ModuleNotFoundError: No module named 'numpy'
2022-09-06T06:39:06.2424303Z * AttributeError: module 'spec2nexus' has no attribute 'utils'
2022-09-06T06:39:06.2424619Z Failed to import spec2nexus.writer.
2022-09-06T06:39:06.2424887Z Possible hints:
2022-09-06T06:39:06.2425484Z * ModuleNotFoundError: No module named 'h5py'
2022-09-06T06:39:06.2426079Z * AttributeError: module 'spec2nexus' has no attribute 'writer'
2022-09-06T06:39:06.2426642Z Failed to import spec2nexus.nexus.
2022-09-06T06:39:06.2426936Z Possible hints:
2022-09-06T06:39:06.2427329Z * AttributeError: module 'spec2nexus' has no attribute 'nexus'
2022-09-06T06:39:06.2427756Z * ModuleNotFoundError: No module named 'numpy'
2022-09-06T06:39:06.2428086Z Failed to import spec2nexus.plugins.XPCS.
2022-09-06T06:39:06.2428368Z Possible hints:
2022-09-06T06:39:06.2428773Z * AttributeError: module 'spec2nexus.plugins' has no attribute 'XPCS'
2022-09-06T06:39:06.2429224Z * ModuleNotFoundError: No module named 'h5py'
2022-09-06T06:39:06.2429541Z Failed to import spec2nexus.eznx.
2022-09-06T06:39:06.2429785Z Possible hints:
2022-09-06T06:39:06.2430188Z * AttributeError: module 'spec2nexus' has no attribute 'eznx'
2022-09-06T06:39:06.2430612Z * ModuleNotFoundError: No module named 'h5py'
2022-09-06T06:39:06.2430905Z Failed to import spec2nexus.spec.
2022-09-06T06:39:06.2431166Z Possible hints:
2022-09-06T06:39:06.2431568Z * AttributeError: module 'spec2nexus' has no attribute 'spec'
2022-09-06T06:39:06.2431979Z * ModuleNotFoundError: No module named 'numpy'
2022-09-06T06:39:06.2432348Z Failed to import spec2nexus.plugins.apstools_specwriter.
2022-09-06T06:39:06.2432660Z Possible hints:
2022-09-06T06:39:06.2433107Z * AttributeError: module 'spec2nexus.plugins' has no attribute 'apstools_specwriter'
2022-09-06T06:39:06.2433586Z * ModuleNotFoundError: No module named 'h5py'
2022-09-06T06:39:06.2433904Z Failed to import spec2nexus.specplot.
2022-09-06T06:39:06.2434176Z Possible hints:
2022-09-06T06:39:06.2434565Z * AttributeError: module 'spec2nexus' has no attribute 'specplot'
2022-09-06T06:39:06.2434995Z * ModuleNotFoundError: No module named 'numpy'
2022-09-06T06:39:06.2435514Z Failed to import spec2nexus.plugins.fallback.
2022-09-06T06:39:06.2435793Z Possible hints:
2022-09-06T06:39:06.2436321Z * AttributeError: module 'spec2nexus.plugins' has no attribute 'fallback'
2022-09-06T06:39:06.2436923Z * ModuleNotFoundError: No module named 'h5py'
2022-09-06T06:39:06.2437255Z Failed to import spec2nexus.plugins.unicat.
2022-09-06T06:39:06.2437555Z Possible hints:
2022-09-06T06:39:06.2437999Z * AttributeError: module 'spec2nexus.plugins' has no attribute 'unicat'
2022-09-06T06:39:06.2438444Z * ModuleNotFoundError: No module named 'h5py'
2022-09-06T06:39:06.2438800Z building [mo]: targets for 0 po files that are out of date
2022-09-06T06:39:06.2439173Z building [html]: targets for 52 source files that are out of date
2022-09-06T06:39:06.2439550Z updating environment: [new config] 52 added, 0 changed, 0 removed
2022-09-06T06:39:06.2439987Z reading sources... [  1%] api
```

</details>


Summary: `Failed to import ` lots of parts, thus documentation is missing.

**Comment by prjemian** [comment]
[`act`](https://github.com/nektos/act) is a great tool for testing GitHub Actions workflows.  First problem it finds:

```
[Publish Sphinx Docs to GitHub Pages/build-docs]   🐳  docker exec cmd=[bash --noprofile --norc -e -o pipefail /var/run/act/workflow/1] user= workdir=
| /var/run/act/workflow/1: line 2: pip: command not found
```

**Comment by prjemian** [comment]
With `pip` installed, the next problem:

```
[Publish Sphinx Docs to GitHub Pages/build-docs]   ❓  ::group:: Running Sphinx builder
| Running Sphinx v5.1.1
| 
| Configuration error:
| There is a programmable error in your configuration file:
| 
| Traceback (most recent call last):
|   File "/usr/local/lib/python3.8/dist-packages/sphinx/config.py", line 347, in eval_config_file
|     exec(code, namespace)
|   File "/home/zorinvm/Documents/projects/prjemian/spec2nexus/docs/source/conf.py", line 13, in <module>
|     import spec2nexus
| ModuleNotFoundError: No module named 'spec2nexus'
| 
| Error: Invalid status code: 2
```

Note the workflow uses `sphinx-notes/pages@master` which is not the latest [`sphinx-notes/pages@v2`](https://github.com/sphinx-notes/pages)

**Comment by prjemian** [comment]
With the workflow action update, the next problem is:

```
| ERROR: Could not find a version that satisfies the requirement matplotlib-base (from -r /home/zorinvm/Documents/projects/prjemian/spec2nexus/././requirements.txt (line 3)) (from versions: none)
| ERROR: No matching distribution found for matplotlib-base (from -r /home/zorinvm/Documents/projects/prjemian/spec2nexus/././requirements.txt (line 3))
```

That's [true](https://pypi.org/search/?q=matplotlib-base) so change to `matplotlib`.

**Comment by prjemian** [comment]
This error again:

```
[Publish Sphinx Docs to GitHub Pages/build-docs]   ❓  ::group:: Running Sphinx builder
| Running Sphinx v5.1.1
| 
| Configuration error:
| There is a programmable error in your configuration file:
| 
| Traceback (most recent call last):
|   File "/usr/local/lib/python3.8/dist-packages/sphinx/config.py", line 347, in eval_config_file
|     exec(code, namespace)
|   File "/home/zorinvm/Documents/projects/prjemian/spec2nexus/docs/source/conf.py", line 13, in <module>
|     import spec2nexus
| ModuleNotFoundError: No module named 'spec2nexus'
| 
```

**Comment by prjemian** [comment]
The root cause was the source file rearrangement of [`src/spec2nexus` -> `spec2nexus`](https://github.com/prjemian/spec2nexus/commit/6cc68c833bf6b5356a56007c9ff3769c945fe972).
