### ISSUE TITLE
extractSpecScan: list index out of range

### ISSUE THREAD

**Issue by prjemian** [prjemian/spec2nexus#64]
resolve the problem as described in https://github.com/BCDA-APS/specplots/issues/3

**Comment by prjemian** [comment]
full error message:

        Traceback (most recent call last):
          File "C:\Users\Pete\Documents\eclipse\spec2nexus\tests\issue64.py", line 47, in test_extractSpecScane
            spec2nexus.extractSpecScan.main()
          File "C:\Users\Pete\Documents\eclipse\spec2nexus\src\spec2nexus\extractSpecScan.py", line 237, in main
            if label in scan.L:
          File "C:\Users\Pete\Documents\eclipse\spec2nexus\src\spec2nexus\spec.py", line 455, in __getattribute__
            self.interpret()
          File "C:\Users\Pete\Documents\eclipse\spec2nexus\src\spec2nexus\spec.py", line 488, in interpret
            func(self)
          File "C:\Users\Pete\Documents\eclipse\spec2nexus\src\spec2nexus\plugins\spec_common_spec2nexus.py", line 556, in postprocess
            mne = scan.header.O[row][col]
        IndexError: list index out of range
