### ISSUE TITLE
test_specplot_gallery: unit test fails on Windows

### ISSUE THREAD

**Issue by prjemian** [prjemian/spec2nexus#81]
looks like the *logging* package f log file is still open:

	E......
	======================================================================
	ERROR: test_command_line_NeXus_writer_1_3 (__main__.SpecPlotGallery)
	----------------------------------------------------------------------
	Traceback (most recent call last):
	  File "C:\Users\Pete\Documents\eclipse\spec2nexus\tests\test_specplot_gallery.py", line 45, in tearDown
		shutil.rmtree(self.tempdir)
	  File "D:\Apps\Anaconda\lib\shutil.py", line 252, in rmtree
		onerror(os.remove, fullname, sys.exc_info())
	  File "D:\Apps\Anaconda\lib\shutil.py", line 250, in rmtree
		os.remove(fullname)
	WindowsError: [Error 32] The process cannot access the file because it is being used by another process: 'c:\\users\\pete\\appdata\\local\\temp\\tmphum9h4\\specplot_files_processing.log'

	----------------------------------------------------------------------
	Ran 7 tests in 40.579s

	FAILED (errors=1)

**Comment by prjemian** [comment]
see: http://stackoverflow.com/questions/5255657/how-can-i-disable-logging-while-running-unit-tests-in-python-django

pick the selected answer and implement

**Comment by prjemian** [comment]
That alone does not solve it.  Add `logging.shutdown()` in the `tearDown()` to resolve.  Hope there are no consequences from this.  At least all tests (for *spec2nexus*) pass on Windows now.
