### ISSUE TITLE
specplot_gallery: no plots of hklscan from file lmn40.spe

### ISSUE THREAD

**Issue by prjemian** [prjemian/spec2nexus#99]
this command:

    specplot_gallery -d /tmp/www lmn40.spe 33id_spec.dat

such as scan "#205" aborted after 71 points of 75 expected, no .png file generated, no error report either

only this report:

1 scan(s) with plotting problems

    IndexError: #S 244 hklscan 2.53365e-07 2.53365e-07 -0.5 -0.5 7 7 45 -200000

**Comment by prjemian** [comment]
same problem for file: 33id_spec.dat

Both of these were run on gov.aps.anl.gov (RHEL7)

**Comment by prjemian** [comment]
no error message or plot from this command either:

    jemian@gov .../02/lmn40 $ specplot  lmn40.spe 64 s00064.png

**Comment by prjemian** [comment]
Looks like an old problem (#64) returns:

    jemian@gov .../02/lmn40 $ specplot  lmn40.spe 244 img.png
    Traceback (most recent call last):
      File "/home/oxygen/JEMIAN/Apps/anaconda/bin/specplot", line 6, in <module>
    	sys.exit(spec2nexus.specplot.main())
      File "/local/Apps/anaconda/lib/python2.7/site-packages/spec2nexus/specplot.py", line 758, in main
    	plotter.plot_scan(scan, args.plotFile)
      File "/local/Apps/anaconda/lib/python2.7/site-packages/spec2nexus/specplot.py", line 388, in plot_scan
    	self.plot_options()
      File "/local/Apps/anaconda/lib/python2.7/site-packages/spec2nexus/specplot.py", line 525, in plot_options
    	self.x_title() or self.set_x_title(self.axes[0])
    IndexError: list index out of range
